robot_base_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

flipkart_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    publish_rate: 50
    
    left_wheel: ['rear_left_joint','front_left_joint']
    right_wheel: ['front_right_joint','rear_right_joint']
    
    wheel_separation: 0.012
    
    # Odometry covariances for the encoder output of the robot. These values should
    # be tuned to your robot's sample odometry data, but these values are a good place
    # to start
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    
    # Top level frame (link) of the robot description
    base_frame_id: base_link
    
    # Velocity and acceleration limits for the robot
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 2   # m/s
        min_velocity           : -0.2 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.6   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 2.0   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 6.0   # rad/s^2

/gazebo_ros_control:
  pid_gains:
    front_right_joint:
      p: 0.009
      i: 8
      d: 0
    front_left_joint:
      p: 0.009
      i: 8
      d: 0
    rear_right_joint:
      p: 0.009
      i: 8
      d: 0
    rear_left_joint:
      p: 0.009
      i: 8
      d: 0